# Generated by Django 4.2.4 on 2024-06-22 07:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('Adminid', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('Adminpass', models.TextField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('Eventname', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('Eventdescription', models.CharField(max_length=100)),
                ('EventDate', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('Facilityname', models.CharField(max_length=255, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('Studentid', models.AutoField(primary_key=True, serialize=False)),
                ('Studentpass', models.TextField(max_length=20)),
                ('Studentname', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_date', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coq.event')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coq.student')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('bookingid', models.AutoField(primary_key=True, serialize=False)),
                ('booking_date', models.DateTimeField(auto_now_add=True)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coq.facility')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coq.student')),
            ],
        ),
    ]
